apiVersion: v1
kind: Secret
metadata:
  name: kapacitor-kafka-connect
  namespace: #{AKS-KC-NAMESPACE}#
type: Opaque
stringData:
  SR_API_KEY: #{SR-KC-KEY}#
  SR_API_SECRET: #{SR-KC-SECRET}#
  SR_URL: #{SR-URL}#
  KC_API_KEY: #{KC-KC-KEY}#
  KC_API_SECRET: #{KC-KC-SECRET}#
  KC_URL: #{KC-URL}#
---
apiVersion: v1
kind: Secret
metadata:
  name: kapacitoracr
  namespace: #{AKS-KC-NAMESPACE}#
type: kubernetes.io/dockerconfigjson
data: 
  .dockerconfigjson: #{ACR-DOCKERCONFIG}#